# Generated by Django 5.1.2 on 2024-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(default='This is the main introduction'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
