# Generated by Django 5.1.2 on 2024-10-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
