# Generated by Django 5.1.2 on 2024-10-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
    ]
