# Generated by Django 5.1.2 on 2024-10-21 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_categories_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
