# Generated by Django 5.1.2 on 2024-10-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_blog_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
    ]
