# Generated by Django 5.1.2 on 2024-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_remove_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
